### ISSUE TITLE
address Skaffold bypassing

### ISSUE THREAD

**Issue by shipperizer** [canonical/identity-platform-admin-ui#181]
the change introduced in https://github.com/canonical/identity-platform-admin-ui/pull/157/commits/0d81544849133ea268e55c3338b4131d0a2e61b4 bypasses skaffold

this needs to be corrected and lead to a refactoring of the `skaffold.yaml` to move dependencies into a specific `profile` and then run 2 separate commands inside the `dev` Makefile target so that we can create a sequenced deployment

**Comment by nsklikas** [comment]
Fixed by https://github.com/canonical/identity-platform-admin-ui/pull/184
