### ISSUE TITLE
Handle/fix live workers number in worker pool in case of a `recover` return is not nil

### ISSUE THREAD

**Issue by BarcoMasile** [canonical/identity-platform-admin-ui#262]
## Description
In `internal/pool/pool.go`, the private `consume` function needs to handle the correct number of live goroutines to make sure performance are not degraded in case some goroutine fails the setup phase.

```go
defer func() {
	if r := recover(); r != nil {
		p.logger.Debug("Recovered in consume ", ID.String(), " ", r)
		p.wg.Done()
		return
	}
}()
```

**Comment by shipperizer** [comment]
this will be dealt with by a feature included in the  roadmap 

closing for now
