### ISSUE TITLE
Add basic entitlements to `privileged` OpenFGA user to allow real administrator/superuser privileges on all resources

### ISSUE THREAD

**Issue by BarcoMasile** [canonical/identity-platform-admin-ui#282]
When creating the authorization model in OpenFGA, populate the store with the following tuples to allow a newly run instance of admin ui to work without additional setup needed in OpenFGA.
This allows to have a "super user" from the get go.

```  
  - user: privileged:superuser
    relation: privileged
    object: provider:global
  - user: privileged:superuser
    relation: privileged
    object: role:global
  - user: privileged:superuser
    relation: privileged
    object: group:global
  - user: privileged:superuser
    relation: privileged
    object: client:global
  - user: privileged:superuser
    relation: privileged
    object: identity:global
  - user: privileged:superuser
    relation: privileged
    object: scheme:global
```

**Comment by nsklikas** [comment]
I think that this was implemented by https://github.com/canonical/identity-platform-admin-ui/pull/370 and https://github.com/canonical/identity-platform-admin-ui/pull/339, can we close it @BarcoMasile?
