### ISSUE TITLE
Broken status API

### ISSUE THREAD

**Issue by nsklikas** [canonical/identity-platform-admin-ui#316]
When I navigate to the status page I get this response 
![image](https://github.com/canonical/identity-platform-admin-ui/assets/19745916/3e2867f3-3ed1-4579-a13c-dc35b8b3e155)

In server throws this error every time a call is made to the status API:
```
http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98)
```

(The `span.End` is not deferred, but that's not what is causing this issue)

**Comment by shipperizer** [comment]
linked to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5438
