### ISSUE TITLE
Consider improving the validation logic for each endpoint

### ISSUE THREAD

**Issue by wood-push-melon** [canonical/identity-platform-admin-ui#352]
Currently, the payload validation logic piles validation for each endpoint in a package, e.g. [the validation in the `group` package](https://github.com/canonical/identity-platform-admin-ui/blob/main/pkg/groups/validation.go#L37-L99).

It's somehow risky whenever endpoints are added and removed. (open/closed principle)

It should be improved. Some OOP design patterns might be helpful (e.g. strategy pattern).

**Comment by shipperizer** [comment]
a new set of API will deal with validation in a different manner, `v0` API can stick with the current setup and avoid refactoring for the time being
