### ISSUE TITLE
List IDPs endpoint returning null breaks UI 

### ISSUE THREAD

**Issue by shipperizer** [canonical/identity-platform-admin-ui#388]
calls from the frontend break when there is no custom IDP created via the frontend (standard case at bootstrap)

this is due to how the ui doesn't handle the `null` data

![image](https://github.com/user-attachments/assets/d7a44c2e-018e-472f-aa01-e6d8378adb73)

```
HTTP https://iam.dev.canonical.com/stg-identity-jaas-dev-admin-ui/api/v0/idps 

{"data":null,"message":"List of IDPs","status":200,"_meta":null}

```

makes sense to have an empty list in case of no data anyway

**Comment by shipperizer** [comment]
@edlerd we are making a fix for this, wondering if UI should be able to handle `null` payloads more gracefully?

**Comment by edlerd** [comment]
> @edlerd we are making a fix for this, wondering if UI should be able to handle `null` payloads more gracefully?

Yes, I think it should. Notifying @huwshimi and @vladimir-cucu who are currently handling the UI work.
